sets read_write_scope from opts, this will permit to comply to readOn…
athonet-open/open_api_spex pull request #3
Opened 2022-09-13 12:51 UTC by juantascon

…ly parameters

2022-09-13 13:45 UTC, riccardomanfrin commented
Thumbup, makes sense to me

2022-09-13 16:39 UTC, albertored requested changes
Can you add the same option to the `OpenApiSpex.Cast.cast/4` function and to the the `OpenApiSpex.cast_value/3,4` ones? 

Also I just noticed that the `:apply_defaults` option that is available in `OpenApiSpex.Cast.cast/4` is not available in `OpenApiSpex.cast_value/3,4`, can you add it in the context of this PR, it should be straightforward.

2022-09-14 09:14 UTC, juantascon commented
I don't get this, OpenApiSpex.Cast.cast/4 already has the parameter, also there is no OpenApiSpex.cast_value/4 and OpenApiSpex.cast_value/3 doesn't have a opts parameter

2022-09-14 12:25 UTC, albertored commented on lib/open_api_spex/cast.ex
>    @spec cast(schema_or_reference | nil, term(), map(), [cast_opt()]) ::
`cast_opt()` type should include the new option

2022-09-15 10:15 UTC, merged